export { authService, AuthService, LocalAuthProvider } from './AuthService';
export type { IAuthProvider, RegisterInput } from './AuthService';
export { billingService, BillingService } from './BillingService';
export type { CheckoutOptions } from './BillingService';
export { printerService, PrinterService, PdfPrintStrategy, BluetoothPrintStrategy } from './PrinterService';
export type { IPrintStrategy, PrintResult, PrinterStrategyId } from './PrinterService';
export { reportService, ReportService } from './ReportService';
export type { DashboardData } from './ReportService';
export { settingsService, SettingsService } from './SettingsService';
export type { AppSettings } from './SettingsService';
export { productService, ProductService } from './ProductService';
export type { ProductInput } from './ProductService';
export { buildReceiptHtml, buildReceiptText } from './receiptTemplate';
export type { ReceiptShopInfo } from './receiptTemplate';
